DROP TABLE IF EXISTS games;

CREATE TABLE games (
    proxyid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game jsonb);

COPY games(game) FROM 'datajson.csv' with (format csv, quote '|', delimiter ';');
